// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatus string

const (
	PrStatusOpen   PrStatus = "open"
	PrStatusMerged PrStatus = "merged"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus
	Valid    bool // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PullRequest struct {
	ID              pgtype.UUID
	PullRequestName string
	AuthorID        pgtype.UUID
	Status          PrStatus
	CreatedAt       pgtype.Timestamp
	MergedAt        pgtype.Timestamp
}

type Team struct {
	ID       pgtype.UUID
	TeamName string
}

type User struct {
	ID                    pgtype.UUID
	Username              string
	TeamID                pgtype.UUID
	IsActive              bool
	AssignedPullRequestID pgtype.UUID
}
