// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type PullRequest struct {
	ID              string
	PullRequestName string
	AuthorID        string
	Status          int16
	CreatedAt       time.Time
	MergedAt        *time.Time
}

type Review struct {
	ID            string
	UserID        string
	PullRequestID string
	Reviewed      bool
}

type Team struct {
	ID       string
	TeamName string
}

type User struct {
	ID       string
	Username string
	TeamID   string
	IsActive bool
}
