// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO team (team_name) VALUES ('Backend Team')
RETURNING id, team_name
`

func (q *Queries) CreateTeam(ctx context.Context) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName)
	return i, err
}
